### ISSUE TITLE
Dashboard Error!  500 Internal Server Error

### ISSUE THREAD

**Issue by mibmit** [intelowlproject/GreedyBear#102]
Hi

Setup a couple of extinsting T-Pots, and looked to add GreedyBear with the /installer_on_tpot.sh  script.

Following execuution of script,  I can load up a page at http://Address:8008 to get the homescreen spash.
When I go for Dashboard.. I get 

![image](https://user-images.githubusercontent.com/6254097/216061956-cba9663b-03ee-45e8-8203-608dbc18ef69.png)

When I try Logon, with the credentials entered in the .sh script, I get "login failed"

Any advice please

Thanks

**Comment by mlodic** [comment]
hey,

surely there is some problem in the installation of GreedyBear in the tpot. I would like to underline that that t-pot installer is an helper that a contributor added but it is not part of the tpot itself so it is not officially supported by the TPOT project. It could not work based on so many different things so you cannot just take it for granted.

What we can do is to help you understand the errors that you have in your application logs but you need to extract them and share them here. Otherwise we are not magicians, you know, we can't guess things just from a 500 random error :P

**Comment by mibmit** [comment]
Hi there

Thanks for update

Yeah, i had seen that T-Pot is not looking like taking on GreedyBear in the future.

As i have had the same issue on multiple T-pot installs, was not sure if the 500 Errror was a common issue, and would have a resolution.

Here is part of /var/log/syslog   searching for 'greedybear' 

If that help point to an issue

Cheers
 Chris


Feb  1 13:45:21 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:45:21.451 UTC [408] ERROR:  relation "greedybear_statistics" does not exist at character 206
Feb  1 13:45:21 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:45:21.451 UTC [408] STATEMENT:  SELECT DATE_TRUNC('hour', "greedybear_statistics"."request_date") AS "date", COUNT(DISTINCT "greedybear_statistics"."source") FILTER (WHERE "greedybear_statistics"."view" = 'enrichment') AS "Sources" FROM "greedybear_statistics" WHERE "greedybear_statistics"."request_date" >= '2023-01-31T13:45:21.437972'::timestamp GROUP BY DATE_TRUNC('hour', "greedybear_statistics"."request_date")
Feb  1 13:52:02 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:52:02.005 UTC [423] ERROR:  relation "greedybear_statistics" does not exist at character 194
Feb  1 13:52:02 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:52:02.005 UTC [423] STATEMENT:  SELECT DATE_TRUNC('hour', "greedybear_statistics"."request_date") AS "date", COUNT("greedybear_statistics"."source") FILTER (WHERE "greedybear_statistics"."view" = 'feeds') AS "Downloads" FROM "greedybear_statistics" WHERE "greedybear_statistics"."request_date" >= '2023-01-31T13:52:01.992654'::timestamp GROUP BY DATE_TRUNC('hour', "greedybear_statistics"."request_date")
Feb  1 13:52:02 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:52:02.007 UTC [424] ERROR:  relation "greedybear_statistics" does not exist at character 201
Feb  1 13:52:02 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:52:02.007 UTC [424] STATEMENT:  SELECT DATE_TRUNC('hour', "greedybear_statistics"."request_date") AS "date", COUNT(DISTINCT "greedybear_statistics"."source") FILTER (WHERE "greedybear_statistics"."view" = 'feeds') AS "Sources" FROM "greedybear_statistics" WHERE "greedybear_statistics"."request_date" >= '2023-01-31T13:52:01.990577'::timestamp GROUP BY DATE_TRUNC('hour', "greedybear_statistics"."request_date")
Feb  1 13:52:02 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:52:02.264 UTC [425] ERROR:  relation "greedybear_statistics" does not exist at character 198
Feb  1 13:52:02 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:52:02.264 UTC [425] STATEMENT:  SELECT DATE_TRUNC('hour', "greedybear_statistics"."request_date") AS "date", COUNT("greedybear_statistics"."source") FILTER (WHERE "greedybear_statistics"."view" = 'enrichment') AS "Requests" FROM "greedybear_statistics" WHERE "greedybear_statistics"."request_date" >= '2023-01-31T13:52:02.253022'::timestamp GROUP BY DATE_TRUNC('hour', "greedybear_statistics"."request_date")
Feb  1 13:52:02 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:52:02.273 UTC [426] ERROR:  relation "greedybear_ioc" does not exist at character 2276
Feb  1 13:52:02 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:52:02.273 UTC [426] STATEMENT:  SELECT DATE_TRUNC('hour', "greedybear_ioc"."last_seen") AS "date", COUNT("greedybear_ioc"."name") FILTER (WHERE "greedybear_ioc"."log4j") AS "Log4j", COUNT("greedybear_ioc"."name") FILTER (WHERE "greedybear_ioc"."cowrie") AS "Cowrie", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%heralding%')) AS "Heralding", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%ciscoasa%')) AS "Ciscoasa", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%honeytrap%')) AS "Honeytrap", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%dionaea%')) AS "Dionaea", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%conpot%')) AS "ConPot", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%adbhoney%')) AS "Adbhoney", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%tanner%')) AS "Tanner", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%citrixhoneypot%')) AS "CitrixHoneypot", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%mailoney%')) AS "Mailoney", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%ipphoney%')) AS "Ipphoney", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%ddospot%')) AS "Ddospot", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%elasticpot%')) AS "ElasticPot", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%dicompot%')) AS "Dicompot", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%redishoneypot%')) AS "Redishoneypot", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%sentrypeer%')) AS "Sentrypeer", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%glutton%')) AS "Glutton" FROM "greedybear_ioc" WHERE "greedybear_ioc"."last_seen" >= '2023-01-31T13:52:02.253990'::timestamp GROUP BY DATE_TRUNC('hour', "greedybear_ioc"."last_seen")
Feb  1 13:52:02 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:52:02.279 UTC [427] ERROR:  relation "greedybear_statistics" does not exist at character 206
Feb  1 13:52:02 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:52:02.279 UTC [427] STATEMENT:  SELECT DATE_TRUNC('hour', "greedybear_statistics"."request_date") AS "date", COUNT(DISTINCT "greedybear_statistics"."source") FILTER (WHERE "greedybear_statistics"."view" = 'enrichment') AS "Sources" FROM "greedybear_statistics" WHERE "greedybear_statistics"."request_date" >= '2023-01-31T13:52:02.262976'::timestamp GROUP BY DATE_TRUNC('hour', "greedybear_statistics"."request_date")
Feb  1 13:52:07 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:52:07.888 UTC [430] ERROR:  relation "greedybear_statistics" does not exist at character 194
Feb  1 13:52:07 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:52:07.888 UTC [430] STATEMENT:  SELECT DATE_TRUNC('hour', "greedybear_statistics"."request_date") AS "date", COUNT("greedybear_statistics"."source") FILTER (WHERE "greedybear_statistics"."view" = 'feeds') AS "Downloads" FROM "greedybear_statistics" WHERE "greedybear_statistics"."request_date" >= '2023-01-31T13:52:07.884152'::timestamp GROUP BY DATE_TRUNC('hour', "greedybear_statistics"."request_date")
Feb  1 13:52:07 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:52:07.889 UTC [428] ERROR:  relation "greedybear_statistics" does not exist at character 201
Feb  1 13:52:07 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:52:07.889 UTC [428] STATEMENT:  SELECT DATE_TRUNC('hour', "greedybear_statistics"."request_date") AS "date", COUNT(DISTINCT "greedybear_statistics"."source") FILTER (WHERE "greedybear_statistics"."view" = 'feeds') AS "Sources" FROM "greedybear_statistics" WHERE "greedybear_statistics"."request_date" >= '2023-01-31T13:52:07.883289'::timestamp GROUP BY DATE_TRUNC('hour', "greedybear_statistics"."request_date")
Feb  1 13:52:07 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:52:07.894 UTC [431] ERROR:  relation "greedybear_ioc" does not exist at character 2276
Feb  1 13:52:07 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:52:07.894 UTC [431] STATEMENT:  SELECT DATE_TRUNC('hour', "greedybear_ioc"."last_seen") AS "date", COUNT("greedybear_ioc"."name") FILTER (WHERE "greedybear_ioc"."log4j") AS "Log4j", COUNT("greedybear_ioc"."name") FILTER (WHERE "greedybear_ioc"."cowrie") AS "Cowrie", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%heralding%')) AS "Heralding", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%ciscoasa%')) AS "Ciscoasa", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%honeytrap%')) AS "Honeytrap", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%dionaea%')) AS "Dionaea", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%conpot%')) AS "ConPot", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%adbhoney%')) AS "Adbhoney", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%tanner%')) AS "Tanner", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%citrixhoneypot%')) AS "CitrixHoneypot", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%mailoney%')) AS "Mailoney", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%ipphoney%')) AS "Ipphoney", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%ddospot%')) AS "Ddospot", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%elasticpot%')) AS "ElasticPot", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%dicompot%')) AS "Dicompot", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%redishoneypot%')) AS "Redishoneypot", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%sentrypeer%')) AS "Sentrypeer", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%glutton%')) AS "Glutton" FROM "greedybear_ioc" WHERE "greedybear_ioc"."last_seen" >= '2023-01-31T13:52:07.883942'::timestamp GROUP BY DATE_TRUNC('hour', "greedybear_ioc"."last_seen")
Feb  1 13:52:07 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:52:07.894 UTC [429] ERROR:  relation "greedybear_statistics" does not exist at character 206
Feb  1 13:52:07 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:52:07.894 UTC [429] STATEMENT:  SELECT DATE_TRUNC('hour', "greedybear_statistics"."request_date") AS "date", COUNT(DISTINCT "greedybear_statistics"."source") FILTER (WHERE "greedybear_statistics"."view" = 'enrichment') AS "Sources" FROM "greedybear_statistics" WHERE "greedybear_statistics"."request_date" >= '2023-01-31T13:52:07.883567'::timestamp GROUP BY DATE_TRUNC('hour', "greedybear_statistics"."request_date")
Feb  1 13:52:07 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:52:07.899 UTC [432] ERROR:  relation "greedybear_statistics" does not exist at character 198
Feb  1 13:52:07 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:52:07.899 UTC [432] STATEMENT:  SELECT DATE_TRUNC('hour', "greedybear_statistics"."request_date") AS "date", COUNT("greedybear_statistics"."source") FILTER (WHERE "greedybear_statistics"."view" = 'enrichment') AS "Requests" FROM "greedybear_statistics" WHERE "greedybear_statistics"."request_date" >= '2023-01-31T13:52:07.886956'::timestamp GROUP BY DATE_TRUNC('hour', "greedybear_statistics"."request_date")
Feb  1 13:53:57 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:53:57.697 UTC [438] ERROR:  relation "greedybear_statistics" does not exist at character 201
Feb  1 13:53:57 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:53:57.697 UTC [438] STATEMENT:  SELECT DATE_TRUNC('hour', "greedybear_statistics"."request_date") AS "date", COUNT(DISTINCT "greedybear_statistics"."source") FILTER (WHERE "greedybear_statistics"."view" = 'feeds') AS "Sources" FROM "greedybear_statistics" WHERE "greedybear_statistics"."request_date" >= '2023-01-31T13:53:57.691348'::timestamp GROUP BY DATE_TRUNC('hour', "greedybear_statistics"."request_date")
Feb  1 13:53:57 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:53:57.699 UTC [439] ERROR:  relation "greedybear_statistics" does not exist at character 206
Feb  1 13:53:57 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:53:57.699 UTC [439] STATEMENT:  SELECT DATE_TRUNC('hour', "greedybear_statistics"."request_date") AS "date", COUNT(DISTINCT "greedybear_statistics"."source") FILTER (WHERE "greedybear_statistics"."view" = 'enrichment') AS "Sources" FROM "greedybear_statistics" WHERE "greedybear_statistics"."request_date" >= '2023-01-31T13:53:57.691893'::timestamp GROUP BY DATE_TRUNC('hour', "greedybear_statistics"."request_date")
Feb  1 13:53:57 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:53:57.702 UTC [440] ERROR:  relation "greedybear_statistics" does not exist at character 198
Feb  1 13:53:57 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:53:57.702 UTC [440] STATEMENT:  SELECT DATE_TRUNC('hour', "greedybear_statistics"."request_date") AS "date", COUNT("greedybear_statistics"."source") FILTER (WHERE "greedybear_statistics"."view" = 'enrichment') AS "Requests" FROM "greedybear_statistics" WHERE "greedybear_statistics"."request_date" >= '2023-01-31T13:53:57.694234'::timestamp GROUP BY DATE_TRUNC('hour', "greedybear_statistics"."request_date")
Feb  1 13:53:57 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:53:57.706 UTC [441] ERROR:  relation "greedybear_ioc" does not exist at character 2276
Feb  1 13:53:57 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:53:57.706 UTC [441] STATEMENT:  SELECT DATE_TRUNC('hour', "greedybear_ioc"."last_seen") AS "date", COUNT("greedybear_ioc"."name") FILTER (WHERE "greedybear_ioc"."log4j") AS "Log4j", COUNT("greedybear_ioc"."name") FILTER (WHERE "greedybear_ioc"."cowrie") AS "Cowrie", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%heralding%')) AS "Heralding", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%ciscoasa%')) AS "Ciscoasa", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%honeytrap%')) AS "Honeytrap", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%dionaea%')) AS "Dionaea", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%conpot%')) AS "ConPot", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%adbhoney%')) AS "Adbhoney", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%tanner%')) AS "Tanner", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%citrixhoneypot%')) AS "CitrixHoneypot", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%mailoney%')) AS "Mailoney", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%ipphoney%')) AS "Ipphoney", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%ddospot%')) AS "Ddospot", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%elasticpot%')) AS "ElasticPot", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%dicompot%')) AS "Dicompot", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%redishoneypot%')) AS "Redishoneypot", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%sentrypeer%')) AS "Sentrypeer", COUNT("greedybear_ioc"."name") FILTER (WHERE UPPER("greedybear_ioc"."general"::text) LIKE UPPER('%glutton%')) AS "Glutton" FROM "greedybear_ioc" WHERE "greedybear_ioc"."last_seen" >= '2023-01-31T13:53:57.691977'::timestamp GROUP BY DATE_TRUNC('hour', "greedybear_ioc"."last_seen")
Feb  1 13:53:57 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:53:57.934 UTC [442] ERROR:  relation "greedybear_statistics" does not exist at character 194
Feb  1 13:53:57 legislativedriver bash[2964]: #033[35mpostgres_1               |#033[0m 2023-02-01 13:53:57.934 UTC [442] STATEMENT:  SELECT DATE_TRUNC('hour', "greedybear_statistics"."request_date") AS "date", COUNT("greedybear_statistics"."source") FILTER (WHERE "greedybear_statistics"."view" = 'feeds') AS "Downloads" FROM "greedybear_statistics" WHERE "greedybear_statistics"."request_date" >= '2023-01-31T13:53:57.924197'::timestamp GROUP BY DATE_TRUNC('hour', "greedybear_statistics"."request_date")

**Comment by mlodic** [comment]
the errors are clear:

* relation "greedybear_statistics" does not exist
* relation "greedybear_ioc" does not exist 

It seems that there is something very wrong in your DB installation. Not sure about what but I'd suggest to go the GreedyBear main directory, destroy the container that contains the db (with `docker-compose down -v`) and then restart the application with `docker-compose up -d` and see if the database has been recreated correctly.

More than this I can't for the reasons I have already explained. You should deploy GB separately from the T-POT by following the easy steps in our doc. That is supported.

Meanwhile I'll add a mention to the doc about the fact that this script is not supported

**Comment by mlodic** [comment]
closed for inactivity
