### ISSUE TITLE
Documentation of how to connect to ElasticSearch is lacking some information

### ISSUE THREAD

**Issue by regulartim** [intelowlproject/GreedyBear#393]
Should GreedyBear run on the same machine as TPot or on a different one?
In the first case there is an issue on Debian that `docker-compose`, which seems to be a requirement for Greedybear, conflicts with the following packages installed by the TPot installer: `containerd.io, docker-ce docker-ce-cli, docker-ce-rootless-extras`.
In the second case, it is not entirely clear how GreedyBear is supposed to connect to the Elastic endpoint. I had to modify TPot's `docker-compose.yml` to expose the ElasticSearch port such that it is accessible to other machines. If that is the intended way, that's fine in my opinion but it should be mentioned in the documentation.

**Comment by mlodic** [comment]
> Should GreedyBear run on the same machine as TPot or on a different one?

Talking with Marco (TPOT Maintainer), we tried to see whether there was any room to _merge_ the 2 projects together. There was also a student who created a script to install GB inside the T-POT itself. 
However, we understood that the integration would have added too many dependencies to the T-POT installation and that GB would have made more sense to be used just as a separated service.

> In the second case, it is not entirely clear how GreedyBear is supposed to connect to the Elastic endpoint. I had to modify TPot's docker-compose.yml to expose the ElasticSearch port such that it is accessible to other machines. If that is the intended way, that's fine in my opinion but it should be mentioned in the documentation.

About that, thanks for asking clarification. I'll add few lines in the doc and let you review

**Comment by mlodic** [comment]
https://github.com/intelowlproject/docs/pull/16 feel free to add changes, I'll invite you to the documentation project.

**Comment by regulartim** [comment]
Alright, thank you!
