### ISSUE TITLE
Feed API slow

### ISSUE THREAD

**Issue by regulartim** [intelowlproject/GreedyBear#394]
Querying the API, e.g. `/api/feeds/all/all/recent.json`, takes a while. Requesting the feed on my GreedyBear instancees with `curl -so /dev/null -w '%{time_total}\n' http://HOSTNAME/api/feeds/all/all/recent.json` takes about 6 seconds. This also produces significant CPU load on the server. However the Honeynet instance seems to be much quicker. Is it just an issue of my installations?

**Comment by mlodic** [comment]
It could probably due to caching mechanisms in Nginx

```
        uwsgi_cache_valid 200 10m;
```

**Comment by regulartim** [comment]
I measured the number of queries sent to the DB when this API endpoint is requested: it's > 5000. I was able to reduce it to 3 by using [prefetch_related](https://docs.djangoproject.com/en/5.1/ref/models/querysets/#prefetch-related). This also dramatically reduces the response time. I'll open a PR tomorrow.

**Comment by regulartim** [comment]
Fixed.
