### ISSUE TITLE
General honeypots always query data from last three days

### ISSUE THREAD

**Issue by regulartim** [intelowlproject/GreedyBear#395]
If one of the supported general honeypots is not active on the underlying TPot instance, `self.first_time_run`  is set to `True` by the `_check_first_time_run` method in `greedybear/cronjobs/attacks.py`. Because all general honeypots are represented by the same instance of the `GeneralHoneypot` class, every time data is extracted from TPot, the last three days are queried. This may result in wrong data.

**Comment by mlodic** [comment]
fixed!
