### ISSUE TITLE
Potentially problematic time filter in Elastic query

### ISSUE THREAD

**Issue by regulartim** [intelowlproject/GreedyBear#403]
There might be a problem in  the Elastic query in `greedybear/cronjobs/base.py`:
```python
q = Q(
            "bool",
            should=[
                Q("range", timestamp={"gte": gte_date, "lte": "now/m"}),
                Q("range", end_time={"gte": gte_date, "lte": "now/m"}),
                Q("range", **{"@timestamp": {"gte": gte_date, "lte": "now/m"}}),
            ],
            minimum_should_match=1,
        )
```

Some entries in Elastic have multiple of the fields that are checked, e.g. the entries from Honeytrap. These fields may have different values. It seems like the `end_time` field uses UTC time while `@timestamp` uses the local time of the TPot instance. This may lead to Greedybear extracting an entry multiple times, once when UTC time matches the criteria and a second time when the local time matches. 

A comment in  `greedybear/cronjobs/base.py` says that this kind of query is necessary due  to honeypots have different column for the time. But when I query my TPot instance, it looks like the `@timestamp` is present for all instances.
```
{
  "query": {
    "bool": {
      "must_not": {
        "exists": {
          "field": "@timestamp"
        }
      }
    }
  }
}
```
This query returns no documents on my instance, so all of the 18 active honeypots seem to use the  `@timestamp`  field.

**Comment by mlodic** [comment]
I think this stuff could have changed over time with new ElasticSearch versions and T-POT releases.

We must remove that for new T-POT versions but, at the same time, this is still useful for the actual T-POTs available in Honeynet.

My opinion is to add a flag (an environment variable) to switch between the standard and simple query that you need and this one that I need with Honeynet.

**Comment by regulartim** [comment]
Will solve this together with #404. Maybe I should ask the people developing TPot if my assumption, that `@timestamp` is always populated, is correct.

**Comment by regulartim** [comment]
Fixed.

**Comment by regulartim** [comment]
> I think this stuff could have changed over time with new ElasticSearch versions and T-POT releases.
> 
> We must remove that for new T-POT versions but, at the same time, this is still useful for the actual T-POTs available in Honeynet.
> 

Marco says, the field should also be present in previous versions: https://github.com/telekom-security/tpotce/discussions/1716
Maybe you could check it on the Honeynet instances some day, then I would remove the legacy code.

**Comment by mlodic** [comment]
I have just tried but I am having trouble accessing it. I'll update you as soon as I manage to log in.
