### ISSUE TITLE
Add interaction count to the IOC model

### ISSUE THREAD

**Issue by regulartim** [intelowlproject/GreedyBear#405]
The IOC model already has a `times_seen` property that counts on how many extraction processes an IOC was extracted. But that does not represent the actual number of the attacker's interactions with the honeypot. But this information might also be valuable in some scenarios.

**Comment by regulartim** [comment]
To make it easier to distinguish between them, maybe we could rename `times_seen` in something like `attack_count` and name the new property `interaction_count`?

**Comment by mlodic** [comment]
agree, there is also the `number_of_days_seen` parameter that is similar and maybe this could stay the same.

In django, a data migration would be required for such change. At the same time, all the other references in the code should be updated

**Comment by regulartim** [comment]
I need to read up on the data migration subject, but I'll give it a try.

**Comment by regulartim** [comment]
Should we maybe keep the old field name in the API for compatibility?

**Comment by mlodic** [comment]
which API are you referring to?

**Comment by regulartim** [comment]
I'm referring to the feeds API. For example for someone who regularly retrieves `/api/feeds/all/all/recent.json` from some GreedyBear instance, renaming a property of the JSON object may break their process. That's why I thought about keeping the old field name in the current feeds API.

**Comment by mlodic** [comment]
you mean whether they have some client doing computation on that field and expecting it, right? 
Well yeah that's possible but we could also add that as a breaking change and make a new major release.

Another option could be to leave that feed like that as you mentioned and then possibly create new feeds with the additional data that you added.

**Comment by regulartim** [comment]
I think I'd prefer the second option. I will revert renaming the field in the JSON feed in #407 and then create a PR for a feeds API v2 later.

**Comment by regulartim** [comment]
After renaming it back at some places I changed my mind. I think this will become too confusing when the same value is called `times_seen` in half of the places and `attack_count` in the other half. Let's add it as a breaking change in a major version together with a reworked feeds API. Do you agree? Sorry for the back and forth.

**Comment by mlodic** [comment]
np yes let's go through that
